# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.1.3
maven_group=madoku.craft.compat
archives_base_name=madoku-craft-compat

# Dependencies
fabric_api_version=0.141.3+1.21.11
madoku_craft_api_version=7754963
madoku_craft_api_mod_version=1.1.5
madoku_craft_items_version=7764686
madoku_craft_attributes_version=7764385
madoku_craft_smelting_version=7764937
madoku_craft_hud_version=7764791
madoku_craft_mobs_version=7765208
