# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.1.1
maven_group=madoku.craft.compat
archives_base_name=madoku-craft-compat

# Dependencies
fabric_api_version=0.141.3+1.21.11
madoku_craft_api_version=7645555
madoku_craft_api_mod_version=1.0.8
madoku_craft_health_version=7653376
madoku_craft_hunger_version=7653332
madoku_craft_armor_version=7645191
madoku_craft_stacks_version=7645682
madoku_craft_smelting_version=7652665
madoku_craft_tools_version=7653420
madoku_craft_hud_version=7650953
madoku_craft_mobs_version=7661639
madoku_craft_difficulty_version=7662192
