org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

mod_version=1.21.11-1.1.5-V3
maven_group=madoku.craft
archives_base_name=madoku-craft-compat

fabric_api_version=0.141.6+1.21.11
core_version=1.21.11-1.3.4-V2
ecosystem_version=1.21.11-1.0.0-V2
attributes_version=1.21.11-1.2.1-V2
levels_version=1.21.11-1.0.4-V2
farming_version=1.21.11-1.0.7-V2
mobs_version=1.21.11-1.0.7-V2
pets_version=1.21.11-1.0.5-V2
hud_version=1.21.11-1.1.4-V2
items_version=1.21.11-1.1.9-V2
utility_version=1.21.11-1.1.0-V2
