pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = "madoku-craft-compat"

if (gradle.parent == null) {
	includeBuild("../core")
	includeBuild("../ecosystem")
	includeBuild("../attributes")
	includeBuild("../levels")
	includeBuild("../farming")
	includeBuild("../mobs")
	includeBuild("../pets")
	includeBuild("../items")
	includeBuild("../utility")
	includeBuild("../hud")
}
